
-- Genres
insert into genres (genre_id, name) values (1, 'Action');
insert into genres (genre_id, name) values (2, 'Adventure');
insert into genres (genre_id, name) values (3, 'Sci-Fi');
insert into genres (genre_id, name) values (4, 'Thriller');
insert into genres (genre_id, name) values (5, 'Comedy');
insert into genres (genre_id, name) values (6, 'Western');
insert into genres (genre_id, name) values (7, 'Animation');
insert into genres (genre_id, name) values (8, 'Family');
insert into genres (genre_id, name) values (9, 'Biography');
insert into genres (genre_id, name) values (10, 'Drama');
insert into genres (genre_id, name) values (11, 'Music');
insert into genres (genre_id, name) values (12, 'War');
insert into genres (genre_id, name) values (13, 'Crime');
insert into genres (genre_id, name) values (14, 'Fantasy');
insert into genres (genre_id, name) values (15, 'Romance');
insert into genres (genre_id, name) values (16, 'History');
insert into genres (genre_id, name) values (17, 'Mystery');
insert into genres (genre_id, name) values (18, 'Horror');
insert into genres (genre_id, name) values (19, 'Sport');
insert into genres (genre_id, name) values (20, 'Documentary');
insert into genres (genre_id, name) values (21, 'Musical');
insert into genres (genre_id, name) values (22, 'News');
insert into genres (genre_id, name) values (23, 'Short');
insert into genres (genre_id, name) values (24, 'Reality-TV');
insert into genres (genre_id, name) values (25, 'Talk-Show');
insert into genres (genre_id, name) values (26, 'Game-Show');
insert into genres (genre_id, name) values (27, 'Film-Noir');
